#plays postgres across all nodes
- name: Install postgres rpm
  yum: name={{postgresql_rpm}} state=present

- name: Install postgres packages
  yum: name={{item}} state=installed
  with_items:
      - postgresql{{postgresql_server_version_name}}-libs
      - postgresql{{postgresql_server_version_name}}
      - postgresql{{postgresql_server_version_name}}-server
      - postgresql{{postgresql_server_version_name}}-contrib
      - postgresql{{postgresql_server_version_name}}-devel

- name: Install python-psycopg2 package
  yum: name=python-psycopg2 state=installed

- name: Existence of postgres configuration file
  stat: path={{postgresql_configuration_file_location}}
  ignore_errors: True
  register: result

- name: Initiating database
  command: service postgresql-{{postgresql_version}} initdb
  when: not result.stat.exists

- name: Start postgres service
  service: name=postgresql-{{postgresql_version}} state=started 

- name: update postgres client configuration
  template: src=pg_hba.conf dest=/var/lib/pgsql/{{postgresql_version}}/data/pg_hba.conf
  notify: restart postgres


- name: postgres should run automatically during system boot
  command: chkconfig postgresql-{{postgresql_version}} on

